params_eval2017:
  gmapi_rev: '4c4fbc1'
  fix_ppp_bug: False
params_dbcreation:
  gmapi_rev: '4c4fbc1'
  dbname: data
  keep_dummy: False
  ops:
    - leave_as_is
params_eval:
  gmapi_rev: '4c4fbc1'
  correct_ppp: True
  legacy_integration: False
  fix_sacs_jacobian: True
  maxiter: 30 
  rtol: 1e-3
  atol: 1e-3
  lmb: 1e-8
  no_reject: False
  no_conv_req: False
  rel_to_std2017: True
